IF OBJECT_ID('tblAreas')IS NOT NULL DROP TABLE tblAreas


GO
CREATE TABLE tblAreas(
	Id INT IDENTITY(1, 1) NOT NULL,
	Code NVARCHAR(1000) NOT NULL,
	Name NVARCHAR(1000) NOT NULL,
	Active BIT NOT NULL CONSTRAINT DF_tblAreasClients_Active DEFAULT(1),
	CONSTRAINT PK_tblAreas PRIMARY KEY (Id),
)


GO
