IF OBJECT_ID('tblZViews')IS NOT NULL DROP TABLE tblZViews


GO
CREATE TABLE tblZViews(
	Id INT IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(1000) NOT NULL,
	Caption NVARCHAR(1000) NOT NULL,
	Category NVARCHAR(1000) NOT NULL,
	XMLCode NVARCHAR(MAX) NOT NULL,
	Active BIT NOT NULL CONSTRAINT DF_tblZViewsClients_Active DEFAULT(1),
	CONSTRAINT PK_tblZViews PRIMARY KEY (Id),
)


GO
